[package]
name = "soduku"
version = "0.1.0"
authors = ["Cheney <sollenberger.15@wright.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
